# Introduction to Pandas

pandas comes preinstalled with Anaconda.  So long you're using an anaconda interpreter, you don't need to install anything extra.

However, if you're using a built in version of python, you might need to install pandas independently as e.g.

pip install pandas

In [1]:
import pandas as pd

# Loading data

Pandas works with "data frames", which can be thought of as a table with rows and columns.

You can load data from many different kinds of file types: csv, xls, html, xml, etc.

In [2]:
df = pd.read_csv('practice_data.csv')

In Jupyter notebook in order to see the data frame, you can call the variable by itslef

In [16]:
df

,Unnamed: 0,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

Some useful commands for seeing a subset of rows of the data frame are 

- head (for seeing the beginning of the data frame)
- tail (for seeing the end of the data frame)

In [20]:
df.head()

,Unnamed: 0,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

In [3]:
df.tail(7)

,Unnamed: 0,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
793,793,717,Yveltal,Dark,Flying,126,131,95,131,98,99,6,True
794,794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True
795,795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

### Working with Columns

You can also view particular columns of the data frame  by indexing the name of the column

In [4]:
df['Name'] # get the entire column

0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3      VenusaurMega Venusaur
4                 Charmander
               ...
795                  Diancie
796      DiancieMega Diancie
797      HoopaHoopa Confined
798       HoopaHoopa Unbound
799                Volcanion
Name: Name, Length: 800, dtype: object

In [25]:
df['Name'][4:9] # get rows 4 through 8 of the column

4                   Charmander
5                   Charmeleon
6                    Charizard
7    CharizardMega Charizard X
8    CharizardMega Charizard Y
Name: Name, dtype: object

You can get multiple columns from a dataframe by indexing a *list* of column names

In [27]:
df[['Name', 'Type 1']][4:9]

                        Name Type 1
4                 Charmander   Fire
5                 Charmeleon   Fire
6                  Charizard   Fire
7  CharizardMega Charizard X   Fire
8  CharizardMega Charizard Y   Fire

### Working with rows

besides head() and tail() you can get any subset of rows using iloc(), which stands for integer location

In [5]:
# get rows 20 to 25
df.iloc[20:26]

,Unnamed: 0,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
20,20,16,Pidgey,Normal,Flying,40,45,40,35,35,56,1,False
21,21,17,Pidgeotto,Normal,Flying,63,60,55,50,50,71,1,False
22,22,18,Pidgeot,Normal,Flying,83,80,75,70,70,101,1,False
23,23,18,PidgeotMega Pidgeot,Normal,Flying,83,80,80,135,80,121,1,False
24,24,19,Rattata,Normal,NaN,30,56,35,25,35,72,1,False
25,25,20,Raticate,Normal,NaN,55,81,60,50,70,97,1,False

### Getting a particluar cell (by row/column)

df.iloc[rows, cols]

In [30]:
df.iloc[20:26, 5:8]

    HP  Attack  Defense
20  40      45       40
21  63      60       55
22  83      80       75
23  83      80       80
24  30      56       35
25  55      81       60

You can also iterate through each row in a loop

In [6]:
for idx,row in df.iterrows():
    print(idx,row)

0 Unnamed: 0            0
#                     1
Name          Bulbasaur
Type 1            Grass
Type 2           Poison
HP                   45
Attack               49
Defense              49
Sp. Atk              65
Sp. Def              65
Speed                45
Generation            1
Legendary         False
Name: 0, dtype: object
1 Unnamed: 0          1
#                   2
Name          Ivysaur
Type 1          Grass
Type 2         Poison
HP                 60
Attack             62
Defense            63
Sp. Atk            80
Sp. Def            80
Speed              60
Generation          1
Legendary       False
Name: 1, dtype: object
2 Unnamed: 0           2
#                    3
Name          Venusaur
Type 1           Grass
Type 2          Poison
HP                  80
Attack              82
Defense             83
Sp. Atk            100
Sp. Def            100
Speed               80
Generation           1
Legendary        False
Name: 2, dtype: object
3 Unnamed: 0                        3
#                                 3
Name          VenusaurMega Venusaur
Type 1                        Grass
Type 2                       Poison
HP                               80
Attack                          100
Defense                         123
Sp. Atk                         122
Sp. Def                         120
Speed                            80
Generation                        1
Legendary                     False
Name: 3, dtype: object
4 Unnamed: 0             4
#                      4
Name          Charmander
Type 1              Fire
Type 2               NaN
HP                    39
Attack                52
Defense               43
Sp. Atk               60
Sp. Def               50
Speed                 65
Generation             1
Legendary          False
Name: 4, dtype: object
5 Unnamed: 0             5
#                      5
Name          Charmeleon
Type 1              Fire
Type 2               NaN
HP                    58
Attack                64
Defense               58
Sp. Atk               80
Sp. Def               65
Speed                 80
Generation             1
Legendary          False
Name: 5, dtype: object
6 Unnamed: 0            6
#                     6
Name          Charizard
Type 1             Fire
Type 2           Flying
HP                   78
Attack               84
Defense              78
Sp. Atk             109
Sp. Def              85
Speed               100
Generation            1
Legendary         False
Name: 6, dtype: object
7 Unnamed: 0                            7
#                                     6
Name          CharizardMega Charizard X
Type 1                             Fire
Type 2                           Dragon
HP                                   78
Attack                              130
Defense                             111
Sp. Atk                             130
Sp. Def                              85
Speed                               100
Generation                            1
Legendary                         False
Name: 7, dtype: object
8 Unnamed: 0                            8
#                                     6
Name          CharizardMega Charizard Y
Type 1                             Fire
Type 2                           Flying
HP                                   78
Attack                              104
Defense                              78
Sp. Atk                             159
Sp. Def                             115
Speed                               100
Generation                            1
Legendary                         False
Name: 8, dtype: object
9 Unnamed: 0           9
#                    7
Name          Squirtle
Type 1           Water
Type 2             NaN
HP                  44
Attack              48
Defense             65
Sp. Atk             50
Sp. Def             64
Speed               43
Generation           1
Legendary        False
Name: 9, dtype: object
10 Unnamed: 0           10
#                     8
Name          Wartortle
Type 1            Water
Type 2              NaN
HP                   59
Attack               63
Defense              80
Sp. Atk              65
Sp. Def              80
Speed                58
Generation            1
Legendary         False
Name: 10, dtype: object
11 Unnamed: 0           11
#                     9
Name          Blastoise
Type 1            Water
Type 2              NaN
HP                   79
Attack               83
Defense             100
Sp. Atk              85
Sp. Def             105
Speed                78
Generation            1
Legendary         False
Name: 11, dtype: object
12 Unnamed: 0                         12
#                                   9
Name          BlastoiseMega Blastoise
Type 1                          Water
Type 2                            NaN
HP                                 79
Attack                            103
Defense                           120
Sp. Atk                           135
Sp. Def                           115
Speed                              78
Generation                          1
Legendary                       False
Name: 12, dtype: object
13 Unnamed: 0          13
#                   10
Name          Caterpie
Type 1             Bug
Type 2             NaN
HP                  45
Attack              30
Defense             35
Sp. Atk             20
Sp. Def             20
Speed               45
Generation           1
Legendary        False
Name: 13, dtype: object
14 Unnamed: 0         14
#                  11
Name          Metapod
Type 1            Bug
Type 2            NaN
HP                 50
Attack             20
Defense            55
Sp. Atk            25
Sp. Def            25
Speed              30
Generation          1
Legendary       False
Name: 14, dtype: object
15 Unnamed: 0            15
#                     12
Name          Butterfree
Type 1               Bug
Type 2            Flying
HP                    60
Attack                45
Defense               50
Sp. Atk               90
Sp. Def               80
Speed                 70
Generation             1
Legendary          False
Name: 15, dtype: object
16 Unnamed: 0        16
#                 13
Name          Weedle
Type 1           Bug
Type 2        Poison
HP                40
Attack            35
Defense           30
Sp. Atk           20
Sp. Def           20
Speed             50
Generation         1
Legendary      False
Name: 16, dtype: object
17 Unnamed: 0        17
#                 14
Name          Kakuna
Type 1           Bug
Type 2        Poison
HP                45
Attack            25
Defense           50
Sp. Atk           25
Sp. Def           25
Speed             35
Generation         1
Legendary      False
Name: 17, dtype: object
18 Unnamed: 0          18
#                   15
Name          Beedrill
Type 1             Bug
Type 2          Poison
HP                  65
Attack              90
Defense             40
Sp. Atk             45
Sp. Def             80
Speed               75
Generation           1
Legendary        False
Name: 18, dtype: object
19 Unnamed: 0                       19
#                                15
Name          BeedrillMega Beedrill
Type 1                          Bug
Type 2                       Poison
HP                               65
Attack                          150
Defense                          40
Sp. Atk                          15
Sp. Def                          80
Speed                           145
Generation                        1
Legendary                     False
Name: 19, dtype: object
20 Unnamed: 0        20
#                 16
Name          Pidgey
Type 1        Normal
Type 2        Flying
HP                40
Attack            45
Defense           40
Sp. Atk           35
Sp. Def           35
Speed             56
Generation         1
Legendary      False
Name: 20, dtype: object
21 Unnamed: 0           21
#                    17
Name          Pidgeotto
Type 1           Normal
Type 2           Flying
HP                   63
Attack               60
Defense              55
Sp. Atk              50
Sp. Def              50
Speed                71
Generation            1
Legendary         False
Name: 21, dtype: object
22 Unnamed: 0         22
#                  18
Name          Pidgeot
Type 1         Normal
Type 2         Flying
HP                 83
Attack             80
Defense            75
Sp. Atk            70
Sp. Def            70
Speed             101
Generation          1
Legendary       False
Name: 22, dtype: object
23 Unnamed: 0                     23
#                              18
Name          PidgeotMega Pidgeot
Type 1                     Normal
Type 2                     Flying
HP                             83
Attack                         80
Defense                        80
Sp. Atk                       135
Sp. Def                        80
Speed                         121
Generation                      1
Legendary                   False
Name: 23, dtype: object
24 Unnamed: 0         24
#                  19
Name          Rattata
Type 1         Normal
Type 2            NaN
HP                 30
Attack             56
Defense            35
Sp. Atk            25
Sp. Def            35
Speed              72
Generation          1
Legendary       False
Name: 24, dtype: object
25 Unnamed: 0          25
#                   20
Name          Raticate
Type 1          Normal
Type 2             NaN
HP                  55
Attack              81
Defense             60
Sp. Atk             50
Sp. Def             70
Speed               97
Generation           1
Legendary        False
Name: 25, dtype: object
26 Unnamed: 0         26
#                  21
Name          Spearow
Type 1         Normal
Type 2         Flying
HP                 40
Attack             60
Defense            30
Sp. Atk            31
Sp. Def            31
Speed              70
Generation          1
Legendary       False
Name: 26, dtype: object
27 Unnamed: 0        27
#                 22
Name          Fearow
Type 1        Normal
Type 2        Flying
HP                65
Attack            90
Defense           65
Sp. Atk           61
Sp. Def           61
Speed            100
Generation         1
Legendary      False
Name: 27, dtype: object
28 Unnamed: 0        28
#                 23
Name           Ekans
Type 1        Poison
Type 2           NaN
HP                35
Attack            60
Defense           44
Sp. Atk           40
Sp. Def           54
Speed             55
Generation         1
Legendary      False
Name: 28, dtype: object
29 Unnamed: 0        29
#                 24
Name           Arbok
Type 1        Poison
Type 2           NaN
HP                60
Attack            85
Defense           69
Sp. Atk           65
Sp. Def           79
Speed             80
Generation         1
Legendary      False
Name: 29, dtype: object
30 Unnamed: 0          30
#                   25
Name           Pikachu
Type 1        Electric
Type 2             NaN
HP                  35
Attack              55
Defense             40
Sp. Atk             50
Sp. Def             50
Speed               90
Generation           1
Legendary        False
Name: 30, dtype: object
31 Unnamed: 0          31
#                   26
Name            Raichu
Type 1        Electric
Type 2             NaN
HP                  60
Attack              90
Defense             55
Sp. Atk             90
Sp. Def             80
Speed              110
Generation           1
Legendary        False
Name: 31, dtype: object
32 Unnamed: 0           32
#                    27
Name          Sandshrew
Type 1           Ground
Type 2              NaN
HP                   50
Attack               75
Defense              85
Sp. Atk              20
Sp. Def              30
Speed                40
Generation            1
Legendary         False
Name: 32, dtype: object
33 Unnamed: 0           33
#                    28
Name          Sandslash
Type 1           Ground
Type 2              NaN
HP                   75
Attack              100
Defense             110
Sp. Atk              45
Sp. Def              55
Speed                65
Generation            1
Legendary         False
Name: 33, dtype: object
34 Unnamed: 0                  34
#                           29
Name          Nidoran (Female)
Type 1                  Poison
Type 2                     NaN
HP                          55
Attack                      47
Defense                     52
Sp. Atk                     40
Sp. Def                     40
Speed                       41
Generation                   1
Legendary                False
Name: 34, dtype: object
35 Unnamed: 0          35
#                   30
Name          Nidorina
Type 1          Poison
Type 2             NaN
HP                  70
Attack              62
Defense             67
Sp. Atk             55
Sp. Def             55
Speed               56
Generation           1
Legendary        False
Name: 35, dtype: object
36 Unnamed: 0           36
#                    31
Name          Nidoqueen
Type 1           Poison
Type 2           Ground
HP                   90
Attack               92
Defense              87
Sp. Atk              75
Sp. Def              85
Speed                76
Generation            1
Legendary         False
Name: 36, dtype: object
37 Unnamed: 0                37
#                         32
Name          Nidoran (Male)
Type 1                Poison
Type 2                   NaN
HP                        46
Attack                    57
Defense                   40
Sp. Atk                   40
Sp. Def                   40
Speed                     50
Generation                 1
Legendary              False
Name: 37, dtype: object
38 Unnamed: 0          38
#                   33
Name          Nidorino
Type 1          Poison
Type 2             NaN
HP                  61
Attack              72
Defense             57
Sp. Atk             55
Sp. Def             55
Speed               65
Generation           1
Legendary        False
Name: 38, dtype: object
39 Unnamed: 0          39
#                   34
Name          Nidoking
Type 1          Poison
Type 2          Ground
HP                  81
Attack             102
Defense             77
Sp. Atk             85
Sp. Def             75
Speed               85
Generation           1
Legendary        False
Name: 39, dtype: object
40 Unnamed: 0          40
#                   35
Name          Clefairy
Type 1           Fairy
Type 2             NaN
HP                  70
Attack              45
Defense             48
Sp. Atk             60
Sp. Def             65
Speed               35
Generation           1
Legendary        False
Name: 40, dtype: object
41 Unnamed: 0          41
#                   36
Name          Clefable
Type 1           Fairy
Type 2             NaN
HP                  95
Attack              70
Defense             73
Sp. Atk             95
Sp. Def             90
Speed               60
Generation           1
Legendary        False
Name: 41, dtype: object
42 Unnamed: 0        42
#                 37
Name          Vulpix
Type 1          Fire
Type 2           NaN
HP                38
Attack            41
Defense           40
Sp. Atk           50
Sp. Def           65
Speed             65
Generation         1
Legendary      False
Name: 42, dtype: object
43 Unnamed: 0           43
#                    38
Name          Ninetales
Type 1             Fire
Type 2              NaN
HP                   73
Attack               76
Defense              75
Sp. Atk              81
Sp. Def             100
Speed               100
Generation            1
Legendary         False
Name: 43, dtype: object
44 Unnamed: 0            44
#                     39
Name          Jigglypuff
Type 1            Normal
Type 2             Fairy
HP                   115
Attack                45
Defense               20
Sp. Atk               45
Sp. Def               25
Speed                 20
Generation             1
Legendary          False
Name: 44, dtype: object
45 Unnamed: 0            45
#                     40
Name          Wigglytuff
Type 1            Normal
Type 2             Fairy
HP                   140
Attack                70
Defense               45
Sp. Atk               85
Sp. Def               50
Speed                 45
Generation             1
Legendary          False
Name: 45, dtype: object
46 Unnamed: 0        46
#                 41
Name           Zubat
Type 1        Poison
Type 2        Flying
HP                40
Attack            45
Defense           35
Sp. Atk           30
Sp. Def           40
Speed             55
Generation         1
Legendary      False
Name: 46, dtype: object
47 Unnamed: 0        47
#                 42
Name          Golbat
Type 1        Poison
Type 2        Flying
HP                75
Attack            80
Defense           70
Sp. Atk           65
Sp. Def           75
Speed             90
Generation         1
Legendary      False
Name: 47, dtype: object
48 Unnamed: 0        48
#                 43
Name          Oddish
Type 1         Grass
Type 2        Poison
HP                45
Attack            50
Defense           55
Sp. Atk           75
Sp. Def           65
Speed             30
Generation         1
Legendary      False
Name: 48, dtype: object
49 Unnamed: 0        49
#                 44
Name           Gloom
Type 1         Grass
Type 2        Poison
HP                60
Attack            65
Defense           70
Sp. Atk           85
Sp. Def           75
Speed             40
Generation         1
Legendary      False
Name: 49, dtype: object
50 Unnamed: 0           50
#                    45
Name          Vileplume
Type 1            Grass
Type 2           Poison
HP                   75
Attack               80
Defense              85
Sp. Atk             110
Sp. Def              90
Speed                50
Generation            1
Legendary         False
Name: 50, dtype: object
51 Unnamed: 0       51
#                46
Name          Paras
Type 1          Bug
Type 2        Grass
HP               35
Attack           70
Defense          55
Sp. Atk          45
Sp. Def          55
Speed            25
Generation        1
Legendary     False
Name: 51, dtype: object
52 Unnamed: 0          52
#                   47
Name          Parasect
Type 1             Bug
Type 2           Grass
HP                  60
Attack              95
Defense             80
Sp. Atk             60
Sp. Def             80
Speed               30
Generation           1
Legendary        False
Name: 52, dtype: object
53 Unnamed: 0         53
#                  48
Name          Venonat
Type 1            Bug
Type 2         Poison
HP                 60
Attack             55
Defense            50
Sp. Atk            40
Sp. Def            55
Speed              45
Generation          1
Legendary       False
Name: 53, dtype: object
54 Unnamed: 0          54
#                   49
Name          Venomoth
Type 1             Bug
Type 2          Poison
HP                  70
Attack              65
Defense             60
Sp. Atk             90
Sp. Def             75
Speed               90
Generation           1
Legendary        False
Name: 54, dtype: object
55 Unnamed: 0         55
#                  50
Name          Diglett
Type 1         Ground
Type 2            NaN
HP                 10
Attack             55
Defense            25
Sp. Atk            35
Sp. Def            45
Speed              95
Generation          1
Legendary       False
Name: 55, dtype: object
56 Unnamed: 0         56
#                  51
Name          Dugtrio
Type 1         Ground
Type 2            NaN
HP                 35
Attack             80
Defense            50
Sp. Atk            50
Sp. Def            70
Speed             120
Generation          1
Legendary       False
Name: 56, dtype: object
57 Unnamed: 0        57
#                 52
Name          Meowth
Type 1        Normal
Type 2           NaN
HP                40
Attack            45
Defense           35
Sp. Atk           40
Sp. Def           40
Speed             90
Generation         1
Legendary      False
Name: 57, dtype: object

You can get a subset of rows according to some Boolean condition using the .loc() function

In [32]:
df.loc[df['Type 1'] == 'Fire']

,Unnamed: 0,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
4,4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
5,5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False
6,6,6,Charizard,Fire,Flying,78,84,78,109,85,100,1,False
7,7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False
8,8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False
42,42,37,Vulpix,Fire,NaN,38,41,40,50,65,65,1,False
43,43,38,Ninetales,Fire,NaN,73,76,75,81,100,100,1,False
63,63,58,Growlithe,Fire,NaN,55,70,45,70,50,60,1,False
64,64,59,Arcanine,Fire,NaN,90,110,80,100,80,95,1,False
83,83,77,Ponyta,Fire,NaN,50,85,55,65,65,90,1,False
84,84,78,Rapidash,Fire,NaN,65,100,70,80,80,105,1,False
135,135,126,Magmar,Fire,NaN,65,95,57,100,85,93,1,False
147,147,136,Flareon,Fire,NaN,65,130,60,95,110,65,1,False
158,158,146,Moltres,Fire,Flying,90,100,90,125,85,90,1,True
169,169,155,Cyndaquil,Fire,NaN,39,52,43,60,50,65,2,False
170,170,156,Quilava,Fire,NaN,58,64,58,80,65,80,2,False
171,171,157,Typhlosion,Fire,NaN,78,84,78,109,85,100,2,False
236,236,218,Slugma,Fire,NaN,40,40,40,70,40,20,2,False
237,237,219,Magcargo,Fire,Rock,50,50,120,80,80,30,2,False
259,259,240,Magby,Fire,NaN,45,75,37,70,55,83,2,False
263,263,244,Entei,Fire,NaN,115,115,85,90,75,100,2,True
270,270,250,Ho-oh,Fire,Flying,106,130,90,110,154,90,2,True
276,276,255,Torchic,Fire,NaN,45,60,40,70,50,45,3,False
277,277,256,Combusken,Fire,Fighting,60,85,60,85,60,55,3,False
278,278,257,Blaziken,Fire,Fighting,80,120,70,110,70,80,3,False
279,279,257,BlazikenMega Blaziken,Fire,Fighting,80,160,80,130,80,100,3,False
352,352,322,Numel,Fire,Ground,60,60,40,65,45,35,3,False
353,353,323,Camerupt,Fire,Ground,70,100,70,105,75,40,3,False
354,354,323,CameruptMega Camerupt,Fire,Ground,70,120,100,145,105,20,3,False
355,355,324,Torkoal,Fire,NaN,70,85,140,85,70,20,3,False
435,435,390,Chimchar,Fire,NaN,44,58,44,58,44,61,4,False
436,436,391,Monferno,Fire,Fighting,64,78,52,78,52,81,4,False
437,437,392,Infernape,Fire,Fighting,76,104,71,104,71,108,4,False
518,518,467,Magmortar,Fire,NaN,75,95,67,125,95,83,4,False
542,542,485,Heatran,Fire,Steel,91,90,106,130,106,77,4,True
557,557,498,Tepig,Fire,NaN,65,63,45,45,45,45,5,False
558,558,499,Pignite,Fire,Fighting,90,93,55,70,55,55,5,False
559,559,500,Emboar,Fire,Fighting,110,123,65,100,65,65,5,False
572,572,513,Pansear,Fire,NaN,50,53,48,53,48,64,5,False
573,573,514,Simisear,Fire,NaN,75,98,63,98,63,101,5,False
614,614,554,Darumaka,Fire,NaN,70,90,45,15,45,50,5,False
615,615,555,DarmanitanStandard Mode,Fire,NaN,105,140,55,30,55,95,5,False
616,616,555,DarmanitanZen Mode,Fire,Psychic,105,30,105,140,105,55,5,False
692,692,631,Heatmor,Fire,NaN,85,97,66,105,66,65,5,False
721,721,653,Fennekin,Fire,NaN,40,45,40,62,60,60,6,False
722,722,654,Braixen,Fire,NaN,59,59,58,90,70,73,6,False
723,723,655,Delphox,Fire,Psychic,75,69,72,114,100,104,6,False
730,730,662,Fletchinder,Fire,Flying,62,73,55,56,52,84,6,False
731,731,663,Talonflame,Fire,Flying,78,81,71,74,69,126,6,False
735,735,667,Litleo,Fire,Normal,62,50,58,73,54,72,6,False
736,736,668,Pyroar,Fire,Normal,86,68,72,109,66,106,6,False
799,799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

#### A birds eye view of the data

In [7]:
df.describe()

,Unnamed: 0,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.0000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,399.5000,362.813750,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,231.0844,208.343798,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,0.0000,1.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,199.7500,184.750000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,399.5000,364.500000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,599.2500,539.250000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,799.0000,721.000000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

### Sorting Data

In [35]:
df.sort_values('Name')

,Unnamed: 0,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
510,510,460,Abomasnow,Grass,Ice,90,92,75,92,85,60,4,False
511,511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False
68,68,63,Abra,Psychic,NaN,25,20,15,105,55,90,1,False
392,392,359,Absol,Dark,NaN,65,130,60,75,60,75,3,False
393,393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
632,632,571,Zoroark,Dark,NaN,60,105,60,120,60,105,5,False
631,631,570,Zorua,Dark,NaN,40,65,40,80,40,65,5,False
46,46,41,Zubat,Poison,Flying,40,45,35,30,40,55,1,False
695,695,634,Zweilous,Dark,Dragon,72,85,70,65,70,58,5,False
794,794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True

You can also sort in descending order

In [39]:
df.sort_values('Name', ascending=False)

,Unnamed: 0,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
794,794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True
695,695,634,Zweilous,Dark,Dragon,72,85,70,65,70,58,5,False
46,46,41,Zubat,Poison,Flying,40,45,35,30,40,55,1,False
631,631,570,Zorua,Dark,NaN,40,65,40,80,40,65,5,False
632,632,571,Zoroark,Dark,NaN,60,105,60,120,60,105,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
393,393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False
392,392,359,Absol,Dark,NaN,65,130,60,75,60,75,3,False
68,68,63,Abra,Psychic,NaN,25,20,15,105,55,90,1,False
511,511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False
510,510,460,Abomasnow,Grass,Ice,90,92,75,92,85,60,4,False

You can also sort according to multiple criteria

In [58]:
df.sort_values(['Type 1', 'HP'], ascending=[True, False])

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Overall score
520,Yanmega,Bug,Flying,86,76,86,116,56,95,4,False,343
698,Volcarona,Bug,Fire,85,60,65,135,105,100,5,False,310
231,Heracross,Bug,Fighting,80,125,75,40,95,85,2,False,365
232,HeracrossMega Heracross,Bug,Fighting,80,185,115,40,105,75,2,False,455
678,Accelgor,Bug,NaN,80,70,40,100,60,145,5,False,335
...,...,...,...,...,...,...,...,...,...,...,...,...
106,Krabby,Water,NaN,30,105,90,25,25,50,1,False,275
125,Horsea,Water,NaN,30,40,70,70,25,60,1,False,200
129,Staryu,Water,NaN,30,45,55,70,55,85,1,False,215
139,Magikarp,Water,NaN,20,10,55,15,20,80,1,False,165
381,Feebas,Water,NaN,20,15,20,10,55,80,3,False,135

### Adding a column to the dataframe

In [8]:
df['Overall score'] = df['HP'] + df['Attack'] + df['Defense'] + df['Speed']

df

,Unnamed: 0,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Overall score
0,0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,188
1,1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,245
2,2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,325
3,3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,383
4,4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,199
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,350
796,796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,430
797,797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,320
798,798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,380
799,799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,380

#### Removing a column

In [9]:
df = df.drop(columns='#')

df

,Unnamed: 0,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Overall score
0,0,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,188
1,1,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,245
2,2,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,325
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,383
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,199
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,795,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,350
796,796,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,430
797,797,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,320
798,798,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,380
799,799,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,380

### Saving the CSV

In [10]:
df.to_csv('practice_data_reduced.csv')

The above will save to the CSV the data frame's indices added by pandas.  

You can prevent this using the "index" parameter

In [11]:
df.to_csv('practice_data_reduced_no_index.csv', index=False)

#### Filtering data 

Again, you can filter which rows you are working with using Boolean criteria with the .loc() method.

In [47]:
df.loc[df['Type 1'] == 'Fire']

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Overall score
4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,199
5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False,260
6,Charizard,Fire,Flying,78,84,78,109,85,100,1,False,340
7,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False,419
8,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False,360
42,Vulpix,Fire,NaN,38,41,40,50,65,65,1,False,184
43,Ninetales,Fire,NaN,73,76,75,81,100,100,1,False,324
63,Growlithe,Fire,NaN,55,70,45,70,50,60,1,False,230
64,Arcanine,Fire,NaN,90,110,80,100,80,95,1,False,375
83,Ponyta,Fire,NaN,50,85,55,65,65,90,1,False,280
84,Rapidash,Fire,NaN,65,100,70,80,80,105,1,False,340
135,Magmar,Fire,NaN,65,95,57,100,85,93,1,False,310
147,Flareon,Fire,NaN,65,130,60,95,110,65,1,False,320
158,Moltres,Fire,Flying,90,100,90,125,85,90,1,True,370
169,Cyndaquil,Fire,NaN,39,52,43,60,50,65,2,False,199
170,Quilava,Fire,NaN,58,64,58,80,65,80,2,False,260
171,Typhlosion,Fire,NaN,78,84,78,109,85,100,2,False,340
236,Slugma,Fire,NaN,40,40,40,70,40,20,2,False,140
237,Magcargo,Fire,Rock,50,50,120,80,80,30,2,False,250
259,Magby,Fire,NaN,45,75,37,70,55,83,2,False,240
263,Entei,Fire,NaN,115,115,85,90,75,100,2,True,415
270,Ho-oh,Fire,Flying,106,130,90,110,154,90,2,True,416
276,Torchic,Fire,NaN,45,60,40,70,50,45,3,False,190
277,Combusken,Fire,Fighting,60,85,60,85,60,55,3,False,260
278,Blaziken,Fire,Fighting,80,120,70,110,70,80,3,False,350
279,BlazikenMega Blaziken,Fire,Fighting,80,160,80,130,80,100,3,False,420
352,Numel,Fire,Ground,60,60,40,65,45,35,3,False,195
353,Camerupt,Fire,Ground,70,100,70,105,75,40,3,False,280
354,CameruptMega Camerupt,Fire,Ground,70,120,100,145,105,20,3,False,310
355,Torkoal,Fire,NaN,70,85,140,85,70,20,3,False,315
435,Chimchar,Fire,NaN,44,58,44,58,44,61,4,False,207
436,Monferno,Fire,Fighting,64,78,52,78,52,81,4,False,275
437,Infernape,Fire,Fighting,76,104,71,104,71,108,4,False,359
518,Magmortar,Fire,NaN,75,95,67,125,95,83,4,False,320
542,Heatran,Fire,Steel,91,90,106,130,106,77,4,True,364
557,Tepig,Fire,NaN,65,63,45,45,45,45,5,False,218
558,Pignite,Fire,Fighting,90,93,55,70,55,55,5,False,293
559,Emboar,Fire,Fighting,110,123,65,100,65,65,5,False,363
572,Pansear,Fire,NaN,50,53,48,53,48,64,5,False,215
573,Simisear,Fire,NaN,75,98,63,98,63,101,5,False,337
614,Darumaka,Fire,NaN,70,90,45,15,45,50,5,False,255
615,DarmanitanStandard Mode,Fire,NaN,105,140,55,30,55,95,5,False,395
616,DarmanitanZen Mode,Fire,Psychic,105,30,105,140,105,55,5,False,295
692,Heatmor,Fire,NaN,85,97,66,105,66,65,5,False,313
721,Fennekin,Fire,NaN,40,45,40,62,60,60,6,False,185
722,Braixen,Fire,NaN,59,59,58,90,70,73,6,False,249
723,Delphox,Fire,Psychic,75,69,72,114,100,104,6,False,320
730,Fletchinder,Fire,Flying,62,73,55,56,52,84,6,False,274
731,Talonflame,Fire,Flying,78,81,71,74,69,126,6,False,356
735,Litleo,Fire,Normal,62,50,58,73,54,72,6,False,242
736,Pyroar,Fire,Normal,86,68,72,109,66,106,6,False,332
799,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,380

You can filter by multiple critera by chaining together Boolean expressions.

Note, in pandas these quantifiers:

& is used for AND

| is used for OR

~ is used for NOT

In [50]:
df.loc[(df['Type 1'] == 'Fire') & (df['Type 2'] == 'Dragon')]

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Overall score
7,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False,419

In [51]:
df.loc[(df['Type 1'] == 'Fire') | (df['Type 2'] == 'Dragon')]

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Overall score
4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,199
5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False,260
6,Charizard,Fire,Flying,78,84,78,109,85,100,1,False,340
7,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False,419
8,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False,360
...,...,...,...,...,...,...,...,...,...,...,...,...
766,Tyrunt,Rock,Dragon,58,89,77,45,45,48,6,False,272
767,Tyrantrum,Rock,Dragon,82,121,119,69,59,71,6,False,393
790,Noibat,Flying,Dragon,40,30,35,45,40,55,6,False,160
791,Noivern,Flying,Dragon,85,70,80,97,80,123,6,False,358
799,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,380

In [52]:
df.loc[~(df['Type 1'] == 'Fire')]

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Overall score
0,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,188
1,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,245
2,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,325
3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,383
9,Squirtle,Water,NaN,44,48,65,50,64,43,1,False,200
...,...,...,...,...,...,...,...,...,...,...,...,...
794,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True,424
795,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,350
796,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,430
797,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,320
798,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,380

Above, the indices are "all over the place".  However, you can reset them so that they range from 0 to the length of the dataframe

In [57]:
my_df = df.loc[~(df['Type 1'] == 'Fire')]

# my_df.drop(columns='index')

my_df.reset_index()

,index,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Overall score
0,0,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,188
1,1,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,245
2,2,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,325
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,383
4,9,Squirtle,Water,NaN,44,48,65,50,64,43,1,False,200
...,...,...,...,...,...,...,...,...,...,...,...,...,...
743,794,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True,424
744,795,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,350
745,796,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,430
746,797,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,320
747,798,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,380